apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "example"
spec:
  size: 3
  config:
    initLimit: 10
    tickTime: 2000
    syncLimit: 2
  image:
    repository: zookeeper
    tag: 3.5.4-beta
    pullPolicy: IfNotPresent
  labels: {}
  ports:
  - name: client
    hostPort:      2181
    containerPort: 2181
  - name: quorum
    hostPort:      2888
    containerPort: 2888
  - name: leader
    hostPort:      3888
    containerPort: 3888
  pod:
    terminationGracePeriodSeconds: 1800,
    labels:
      app: example
    affinity:
      topologyKey: kubernetes.io/hostname
      labelSelector:
      - key: app
        operator: In
        values:
        - example-headless
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
    tolerations: {}
    env: {}
    annotations: {}
    securityContext: {}
  persistence:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
