#!/usr/bin/env bash

HOST=`hostname -s`
DOMAIN=`hostname -d`
MYIDFILE="/data/myid"
DYNCONFIG="/data/zoo.cfg.dynamic"
CLIENTPORT=$1
QUORUMPORT=$2
LEADERPORT=$3

# Extract cluster ordinal value from hostname
if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
  NAME=${BASH_REMATCH[1]}
  ORD=$(( ${BASH_REMATCH[2]} + 1 ))
else
  echo "Failed to extract ordinal from hostname $HOST"
  exit 1
fi

echo "Bootstrapping instance with ordinal value: $ORD"

# Check `myid` file, or write it, if it doesn't exist
if [ -f $MYIDFILE ]; then
  MYID=$(< $MYIDFILE)
  if [[ $MYID -ne $ORD ]]; then
    echo "Host ordinal, ${ORD}, does not match configured id: ${MYID}"
    exit 1
  else
    echo "Cluster ID is set and matches ordinal value"
  fi
else
  echo "Cluster ID not yet set. Setting to $ORD"
  echo $ORD > $MYIDFILE
fi

# If ordinal 0, then generate a starter config
if [[ $ORD -eq 1 ]]; then
  if [ ! -f $DYNCONFIG ]; then
    echo "Dynamic configuration not yet initialized. Initializing now."
    echo "server.${ORD}=${HOST}:${QUORUMPORT}:${LEADERPORT}:participant;$CLIENTPORT" > $DYNCONFIG
  fi
fi
