apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-operator
  namespace: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-operator
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      serviceAccountName: zookeeper-operator
      containers:
        - name: zookeeper-operator
          # Replace this with the built image name
          image: uhub.service.ucloud.cn/infra/zookeeper-operator:v1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - zookeeper-operator
          imagePullPolicy: Always
          env:
          - name: WATCH_NAMESPACE
            value: "zookeeper"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "zookeeper-operator"
          - name: PENDING_TIMEOUT_TIME
            value: "120"
          - name: TERMINATING_TIMEOUT_TIME
            value: "360"
