{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
{{- if or .Values.global.imagePullSecrets .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- range (default .Values.global.imagePullSecrets .Values.serviceAccount.imagePullSecrets) }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zookeeper-operator.commonLabels" . | indent 4 }}
{{- end }}
