{{- if .Values.crd.create }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1" }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.pravega.io
spec:
{{- if not (.Capabilities.APIVersions.Has "apiextensions.k8s.io/v1") }}
{{- include "crd.additionalPrinterColumnsV1Beta" . | indent 2}}
{{- end }}
  group: zookeeper.pravega.io
  names:
    kind: ZookeeperCluster
    listKind: ZookeeperClusterList
    plural: zookeeperclusters
    shortNames:
    - zk
    singular: zookeepercluster
  scope: Namespaced
{{- if not (.Capabilities.APIVersions.Has "apiextensions.k8s.io/v1") }}
  subresources:
    status: {}
  validation:
{{- include "crd.openAPIV3Schema" . | indent 4}}
  version: v1beta1
{{- end }}
  versions:
  - name: v1beta1
    served: true
    storage: true
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1" }}
    subresources:
      status: {}
{{- include "crd.additionalPrinterColumns" . | indent 4}}
    schema:
{{- include "crd.openAPIV3Schema" . | indent 6}}
{{- end }}
{{- end }}
